name: Build TWA AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install Bubblewrap
      run: npm install -g @bubblewrap/cli
      
    - name: Generate keystore
      run: |
        keytool -genkey -v -keystore android.keystore -alias android -keyalg RSA -keysize 2048 -validity 10000 -storepass nobody123 -keypass nobody123 -dname "CN=Nobody Comment, OU=Development, O=Nobody Comment, L=Seoul, S=Seoul, C=KR"
        
    - name: Initialize TWA project
      run: |
        echo -e "nobody-comment.vercel.app\n/\n아무개의 명언 - 가장 보통의 존재들이 쓰는 하루 한마디\n아무개명언\napp.vercel.nobody_comment.twa\n1\nstandalone\nportrait\n#0EA5E9\n#FFFFFF\nhttps://nobody-comment.vercel.app/icon-512x512.png\n\n\nNo\nNo\nandroid.keystore\nandroid" | bubblewrap init --manifest https://nobody-comment.vercel.app/manifest.json
        
    - name: Build AAB
      run: |
        echo -e "nobody123\nnobody123" | bubblewrap build
        
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app-release.aab
