name: Build TWA AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install Bubblewrap
      run: npm install -g @bubblewrap/cli
      
    - name: Test workflow
      run: echo "Workflow is working!"
      
    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-file
        path: README.md
